### ISSUE TITLE
Checkpoints with Image Dataset and NRS

### ISSUE THREAD

**Issue by jdriscoll319** [TRI-ML/packnet-sfm#111]
I'm getting the "checkpoint metric not available" error when I try to save a checkpoint when training with  the Image Dataset on the NRS network. I suspect that this is related to being able to define a `depth_type` in the config `.yaml` but I'm unsure what the workaround would be. I have tried a few different `monitor` types and they all have this same issue. Here is my config:
```
checkpoint:
    filepath: '/data/datasets/blackvue/full/checkpoints'
    monitor: 'abs_rel_pp'
    mode: 'min'
arch:
    max_epochs: 5
model:
    name: 'GenericSelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'RaySurfaceResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (128, 224)
        # image_shape: (96, 256)
    train:
        batch_size: 1
        dataset: ['Image']
        path: ['/data/datasets/blackvue/full/test']
        split: ['{:06}']
        depth_type: ['']
        repeat: [1]
    validation:
        dataset: ['Image']
        path: ['/data/datasets/blackvue/full/test']
        split: ['{:06}']
        depth_type: ['']
    test:
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_tiny']
        split: ['kitti_tiny.txt']
        depth_type: ['velodyne']
```
