### ISSUE TITLE
fine-tune poorly on my own dataset

### ISSUE THREAD

**Issue by XinnWang** [TRI-ML/packnet-sfm#41]
Hi, thanks for the great work ! I am trying to fine-tune the 'PackNet01_MR_selfsup_K.ckpt' on my own dataset, but the performance is not good. Here are some examples:

If i use 'PackNet01_MR_selfsup_K.ckpt' without fine-tune, the result looks like this:
![image](https://user-images.githubusercontent.com/5515327/86346085-ffba5180-bc8e-11ea-9c23-b6f9c9b4c1ac.png)

after fine-tune this model, i get this result:
![image](https://user-images.githubusercontent.com/5515327/86346176-1f517a00-bc8f-11ea-8aa2-ebf2613c4ba2.png)

The following is the yaml file i used for training.
```
arch:
    max_epochs: 10
checkpoint:
    filepath: /workspace/packnet-sfm/results/chept
    save_top_k: -1
model:
    name: 'SelfSupModel'
    checkpoint_path: /data/models/PackNet01_MR_semisup_CStoK.ckpt
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 1
        dataset: ['Image']
        path: ['my_training_dataset']
        split: ['{:03d}']
        repeat: [1]
    validation:
        dataset: ['Image']
        path: ['my_eval_dataset']
        split: ['{:03d}']
    test:
        dataset: ['Image']
        path: ['my_test_dataset']
        split: ['{:03d}']
```

i also changed the dummy_calibration parames inside datasets/image_dataset.py:
```
def dummy_calibration(image):
    w, h = [float(d) for d in image.size]
    return np.array([[343.169585 , 0.    , 321.358181],
                     [0.    , 344.619087, 93.813611],
                     [0.    , 0.    , 1.          ]])
```

My dataset contains 3k images, resolution is (192,640). (only mono images)
The training is done on 4 x Tesla M40, with NVIDIA-SMI 418.56 Driver Version: 418.56 CUDA Version: 10.1
After the training, the 'Avg.Loss' drops from 0.0370 to 0.0350.  (it drops really slow.)

I know my training epochs is too few. i am still training it now. but the Avg.Loss is always around 0.0350. 
Is there any other possible reasons about this poor result? Any help or suggestion will be appreciated. Thanks !
