### ISSUE TITLE
Issue with saving our own checkpoint (.ckp) file after our training

### ISSUE THREAD

**Issue by soheilAppear** [TRI-ML/packnet-sfm#54]
Hi,

I have a question regarding training on my own dataset. I tried to first use tiny_KITTI datasets for training and build my own .ckp file. However, I was not able to do that. I tried to make some changes in the .yaml file and defined the save directory for checkpoints there. However, I could not find it and I do not know how to do it. I appreciate it if you help me.

Thanks,
Soheil.

**Comment by VitorGuizilini-TRI** [comment]
Can you show me the .yaml file you are using? These are the options you should add, with examples:
```
checkpoint:
    filepath: '/data/experiments'
    monitor: 'abs_rel_pp_gt'
    monitor_index: 0
    mode: 'min'
```
