### ISSUE TITLE
Can't find any val and train data

### ISSUE THREAD

**Issue by e2r-htz** [TRI-ML/packnet-sfm#93]
I have the following config

```
model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 4
        dataset: ['KITTI']
        path: ['/data/datasets/kitti-raw']
        split: ['splits/eigen_train_files.txt']
        depth_type: ['velodyne']
        repeat: [2]
    validation:
        dataset: ['KITTI']
        path: ['/data/datasets/kitti-raw']
        split: ['splits/eigen_val_files.txt',
                'splits/eigen_train_files.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['/data/datasets/kitti-raw']
        split: ['splits/eigen_train_files.txt']
        depth_type: ['velodyne']
```

Note that the split file name for train, val and test are pointing to the same file. However, for val and test, these files are not loaded. The print output is as follows

```
### Preparing Model
Model: SelfSupModel
DepthNet: PackNet01
PoseNet: PoseNet
### Preparing Datasets
###### Setup train datasets
#########   45074 (x2): /data/datasets/kitti-raw/splits/eigen_train_files.txt
###### Setup validation datasets
#########       0: /data/datasets/kitti-raw/splits/eigen_val_files.txt
#########       0: /data/datasets/kitti-raw/splits/eigen_train_files.txt
###### Setup test datasets
#########       0: /data/datasets/kitti-raw/splits/eigen_train_files.txt
```

Any help would be appreciated. Thanks
