### ISSUE TITLE
Texture copy artifact problem

### ISSUE THREAD

**Issue by surfii3z** [TRI-ML/packnet-sfm#94]
Hi all

Thank you for sharing this repo, it is an amazing work.

I want to try to use the depth model for monocular depth estimation in the indoor environment.

---------------
The dataset is prepared from TUM rolling shutter dataset. The image is rectified to the size (row, col) = (594, 795) such that the distortion coefficients are all 0 and the principal points are exactly at the centre of the image.
```
np.array([[371.74580354175663 , 0.    , 397.5],
               [0.    , 371.74580354175663 , 297.0],
               0.    , 0.    , 1.          ]])
```
Also, since the network only accepts RGB image as the input. I extend the gray color channel to three dimension so that it can be the input of the neural network. 

---------------
I fine tune the model "PackNet, Self-Supervised Scale-Aware, 192x640, CS → K" with dataset and the following configuration.
```
arch:
    max_epochs: 40

checkpoint:
    # Folder where .ckpt files will be saved during training
    filepath: /workspace/packnet-sfm/results/chept
    save_top_k: -1

model:
    name: 'SelfSupModel'
        checkpoint_path: /workspace/packnet-sfm/trained_models/PackNet01_MR_velsup_CStoK.ckpt
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.000001
        pose:
            lr: 0.000001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        # should be multiple of 32
        image_shape: (352, 480)
        # image_shape: (32, 32)
    train:
        batch_size: 4
        dataset: ['KITTI']
        path: ['/data/datasets/rolling_shutter_rect']
        split: ['train.txt']
        repeat: [2]
    validation:
        dataset: ['KITTI']
        path: ['/data/datasets/rolling_shutter_rect']
        split: ['eval.txt']
```
The result looks like the picture below.

![Screenshot from 2020-11-17 22-07-34](https://user-images.githubusercontent.com/38914643/99394795-cd9a4b00-2922-11eb-9519-7c1daaa00ead.png)

In my opinion, it looks okay-ish, however, I think there are a lot of "texture copy artifact" ,for example, at the April's grid and checker board. Is the result to be expected (because I fine tune the network in the indoor dataset/ the input is gray scale/ the size of data augmentation is quite different with the network input)? Or what approach do you suggest to prevent the artifact? Or such artifact just does not affect the performance of the depth map?
